export const mediaList = [
    // { type: "image", src: "music/bgmusic1.jpg"},
    // { type: "image", src: "music/bgmusic2.jpg"},
    // { type: "image", src: "music/bgmusic3.jpg"},
    // { type: "image", src: "music/bgmusic4.jpg"},
    // { type: "image", src: "music/bgmusic5.jpg"},
    // { type: "image", src: "music/bgmusic6.jpg"},
    // { type: "image", src: "music/bgmusic7.jpg"},
    // { type: "image", src: "music/bgmusic8.jpg"},
    // { type: "image", src: "music/bgmusic9.jpg"},
    // { type: "image", src: "music/bgmusic10.jpg"},
    // { type: "image", src: "music/bgmusic11.jpg"},
    // { type: "image", src: "music/bgmusic12.jpg"},
    { type: "video", src: "music/videomusic1.mp4"},
    { type: "video", src: "music/videomusic2.mp4"},
    { type: "video", src: "music/videomusic3.mp4"},
    { type: "video", src: "music/videomusic4.mp4"},
    { type: "video", src: "music/videomusic5.mp4"},
    { type: "video", src: "music/videomusic6.mp4"},
    { type: "video", src: "music/videomusic7.mp4"},
    { type: "video", src: "music/videomusic8.mp4"},
    { type: "video", src: "music/videomusic9.mp4"},
    { type: "video", src: "music/videomusic10.mp4"},
    { type: "video", src: "music/videomusic11.mp4"},
    { type: "video", src: "music/videomusic12.mp4"},
    { type: "video", src: "music/videomusic13.mp4"},
  ];